model:
  model_name: "distilbert-base-uncased"
  num_labels: 4
  max_length: 256
  batch_size: 16
  learning_rate: 2e-5
  num_epochs: 3

training:
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  save_dir: "./saved_models"
  log_dir: "./logs"

data:
  categories: ["positive", "negative", "urgent", "feature_request"]
  theme_keywords: {
    "billing": ["payment", "charge", "bill", "price", "cost"],
    "technical": ["bug", "crash", "error", "slow", "freeze"],
    "feature": ["add", "request", "suggestion", "improvement"],
    "support": ["help", "assistance", "contact", "response"]
  }

inference:
  confidence_threshold: 0.7